#Basic Configuration
flyway.url=jdbc:snowflake://https://co83606.ap-south-1.aws.snowflakecomputing.com
flyway.user=PVENKATESH
flyway.initSql=USE ROLE ACCOUNTADMIN; USE WAREHOUSE COMPUTE_WH; USE DATABASE FLYWAY; USE SCHEMA UTIL;
flyway.locations=filesystem:sql

#Placeholders
flyway.placeholders.publicSchema=PUBLIC