name: Flyway Migration CI/CD

on:
  push:
    branches:
      - dev
      - test
      - main
  
  # pull_request:
  #   branches:
  #     - dev
      # - test
      # - main

  # Allows you to run this action manually
  workflow_dispatch:

jobs:
  flyway_migration:
    runs-on: ubuntu-latest

    container:
      image: flyway/flyway

    steps:
      - uses: actions/checkout@v3

      - name: Run Flyway Migration
        shell: bash
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          set -e
          export JAVA_ARGS="--add-opens=java.base/java.nio=ALL-UNNAMED"

          # Extract the branch name 
          BRANCH_NAME="${GITHUB_REF##*/}"

          if [ "$BRANCH_NAME" = "dev" ]; then
            CONFIG_FILE="configs/dev.conf"
          elif [ "$BRANCH_NAME" = "test" ]; then
            CONFIG_FILE="configs/test.conf"
          elif [ "$BRANCH_NAME" = "main" ]; then
            CONFIG_FILE="configs/prod.conf"
          else
            # Fallback if needed
            CONFIG_FILE="configs/dev.conf"
          fi

          echo "Using config file: $CONFIG_FILE"

          flyway -user="$SNOWFLAKE_USER" -password="$SNOWFLAKE_PASSWORD" -configFiles="$CONFIG_FILE" -X migrate